name: Deploy Next.js to S3 for EC2
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'comment'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check if main branch
        run: |
          if [[ "${{ github.ref }}" != 'refs/heads/main' ]]; then
            echo "This workflow can only be run from the main branch."
            exit 1
          fi

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: zip create
        run: zip -qq -r ./next-build.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Upload to AWS S3
        run: |
          aws s3 cp --region ${{ secrets.AWS_DEFAULT_REGION }} ./next-build.zip s3://${{ secrets.S3_BUCKET }}/next-build.zip

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.AWS_APPLICATION_NAME }} \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name ${{ secrets.AWS_DEPLOYMENT_GROUP }} \
            --s3-location bucket=${{ secrets.S3_BUCKET }},key=next-build,bundleType=zip
